# SPDX-License-Identifier: MPL-2.0
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: ["numpy"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/google/addlicense
    rev: v1.1.1
    hooks:
      - id: addlicense
        args:
          - -c
          - "Augusto 'Guto' Ochoa Ughini"
          - -s
          - MPL-2.0
        types_or:
          - python
          - shell
          - yaml
          - toml
          - makefile
          - dockerfile
  - repo: https://github.com/fsfe/reuse-tool
    rev: v3.0.2
    hooks:
      - id: reuse
        name: reuse lint
        entry: reuse lint
        language: python
        additional_dependencies: [reuse]
