# SPDX-License-Identifier: MPL-2.0
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements.lock
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run quality checks
        run: make check

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: |
            coverage.xml
            htmlcov/
          if-no-files-found: ignore

  license-compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install license tooling
        run: |
          python -m pip install --upgrade pip
          pip install reuse scancode-toolkit

      - name: Run REUSE lint
        run: reuse lint

      - name: Run ScanCode license scan
        run: scancode --strip-root --license --summary --json-pp scancode-report.json .

      - name: Upload license scan report
        uses: actions/upload-artifact@v4
        with:
          name: license-scan
          path: scancode-report.json
